### ISSUE TITLE
Add File Support in Discord Adapter for Long Text

### ISSUE THREAD

**Issue by chinmoy12c** [BharatSahAIyak/packages#132]
## Description
This issue tracks the implementation of a feature supporting long text messages on Discord. Currently, the discord adapter is not able to send long text due to restrictions. Although, this can be circumvented by using files. The requirement is to add support for sending long text into files in discord adapter.

### 1. Go through documentation
- **Task**: Checkout what is the length of text accepted by Discord for which it can render the message.
- **Approval**: Get the code reviewed by providing code snippet on how you will be handling this check.

### 2. Implement feature
- **Task**: Implement the above approved feature.

### 3. Error handling
- **Task**: Add error handling to the adapter
- **Details**: Ensure that the feature is thoroughly tested and and have error handling in case of failure.

## Expected Outcomes
- Have a Discord adapter which sends message on a channel, text or file, based on the length of message provided.
- Error handling in case of failure to send message to discord.

## Product Name
packages

## Project Name
packages

## Organization Name
SamagraX

## Domain
NA

## Tech Skills Needed
Node JS

## Category
Feature

## Mentor(s)
@ChakshuGautam 

## Complexity
Low

**Comment by kesharibhai84** [comment]
hi, @ChakshuGautam please assign me this issue want to resolve this

**Comment by trishanu-init** [comment]
@ChakshuGautam  Please assign this issue to me

**Comment by isar-hub** [comment]
PLEASE ASSIGN ISSUE TO ME

**Comment by neeraj542** [comment]
I want to work on this issue under Augtoberfest, C4GT.
Please assign this issue to me if possible.
