### ISSUE TITLE
Clean Up Translation/LLM Transformer

### ISSUE THREAD

**Issue by ChakshuGautam** [BharatSahAIyak/packages#19]
Currently due to streaming blocker, the LLM and Transformer code is messy and not independent. Code needs to be cleaned up once streaming is figured out.

**Comment by dhruv-1001** [comment]
@Amruth-Vamshi to pick this up as well. 
https://github.com/BharatSahAIyak/docs/issues/51

**Comment by ChakshuGautam** [comment]
@chinmoy12c can we add changelog to transformer spec too?

**Comment by chinmoy12c** [comment]
> [@chinmoy12c](https://github.com/chinmoy12c) can we add changelog to transformer spec too?

Spec hasn't changed.

**Comment by techsavvyash** [comment]
@chinmoy12c moving this to blocked this PR can't be merged till H2 2417 as described here - https://github.com/BharatSahAIyak/kisai-bot/issues/423

**Comment by chinmoy12c** [comment]
PR has been relanded.
@Amruth-Vamshi @Sreejit-K @RyanWalker277 to test out flows.
