### ISSUE TITLE
Transformer Registry Marketplace [NodeHub]

### ISSUE THREAD

**Issue by ChakshuGautam** [BharatSahAIyak/packages#27]
- [x] Design (HLD, LLD)
- [ ] Break this down to C4GT Tickets.
- [ ] Create a marketplace for Transformers and Adapters.
- [ ] Create automatically generated docs for transformer types based on json config.
- [ ] Create a guide for specific use cases for transformer instances.
- [ ] Refactor types as a package from transformers.

**Comment by chinmoy12c** [comment]
Currently working on creating marketplace service.
Calling it "nodehub".

**Comment by chinmoy12c** [comment]
Add guide for usage @chinmoy12c
