### ISSUE TITLE
Transformer Expose metadata and config

### ISSUE THREAD

**Issue by chinmoy12c** [BharatSahAIyak/packages#32]
Transformers need to expose `metaData` about rendering and `config` parameters externally, so it can be used by frontend to render corresponding nodes.

pick `config.spec.json`, `metadata.json` from every folder of transformer. Metadata - `name` (`displayName`), `class`, `type`, `desc`, `version` (`latest`, `0.1`, etc)

**Comment by ChakshuGautam** [comment]
- [ ] Config TS Class autogenerated from spec
- [ ] Document the spec ([zod](https://zod.dev/))

**Comment by chinmoy12c** [comment]
Generator/Validator created: https://github.com/BharatSahAIyak/packages/commit/fdf0f5a5f6f040a2e2b39684377032daa2a90dfd

**Comment by chinmoy12c** [comment]
Pr raised for documentation: [PR](https://github.com/BharatSahAIyak/docs/pull/41)
@ChakshuGautam to review
