### ISSUE TITLE
Add media handling for channels

### ISSUE THREAD

**Issue by chinmoy12c** [BharatSahAIyak/packages#64]
Support for incoming media like audio, image, video

- [ ] Create STT node
- [x] Handle other image and video media

**Comment by chinmoy12c** [comment]
PR changes to be incorporated.

**Comment by chinmoy12c** [comment]
API changes for accepting url done. Testing results awaited.

**Comment by dhruv-1001** [comment]
Getting wrong signature for media from Gupshup. Need to setup a call with them to resolve this.

**Comment by chinmoy12c** [comment]
PR: 
https://github.com/BharatSahAIyak/packages/pull/101
https://github.com/BharatSahAIyak/packages/pull/99
