### ISSUE TITLE
Clean up transformers and add unit tests

### ISSUE THREAD

**Issue by chinmoy12c** [BharatSahAIyak/packages#7]
- [x] Define a simplistic interface based on this architecture.

![Image](https://github.com/BharatSahAIyak/packages/assets/57670338/a653fc5e-7f8f-4059-8f85-c609fa6df09c)

- [x] Figure out how xstate would link transformers together, without hardwiring internal flow logic.
- [x] #25
Instead, these should be separate transformers and xstate def should be as simple as:
RUN: T1 -> T2 -> T3 -> END
Instead of saying:
RUN: T1(function A, check condition B, function C) -> T2 (function C) -> T3 (function X, check condition B, check condition C, function Z).

- [x] Hide internal code logic from xstate. As an example this is a portion of xstate currently:
```
"searchSimilarChunks": {
            "invoke": {
                "src": "searchSimilarChunks",
                "onDone": [
                    {
                        "cond": "ifSimilarChunksFound",
                        "target": "llm",
                        "actions": [
                            "searchSimilarChunksRecordResponse"
                        ]
                    },
                    {
                        "target": "end",
                        "actions": [
                            "setNoContextOutput"
                        ]
                    }
                ],
                "onError": "handleError"
            }
        }
    },
```

The xstate directly works on "pure functions" exposed by each of the transformers, this needs to be refactored to only expose generic functionalities "without code level details", for this to seamlessly integrate with flowise.

- [x] If possible move to class/interface based code instead of functional code.
- [ ] Add unit test which injects xstate and verifies function of transformers. (Maybe add boilerplate classes for other transformers to use as well.)

**Comment by RyanWalker277** [comment]
Draft Pr Link: https://github.com/BharatSahAIyak/packages/pull/43

## Progress

### Generic Transformer

- [ ] Code Runner
- [ ] http_get
- [ ] http_post
- [ ] llm
- [ ] neural_corefrence
- [ ] sql query builder
- [ ] translate

### if_else

- [ ] doc retriever
- [ ] random binary

### Retry
 - [ ] simple retry
### state_restore

- [ ] user feedback loop

### switch case

- [ ] label classifier

**Comment by RyanWalker277** [comment]
PR changes done, @chinmoy12c to review and merge
