### ISSUE TITLE
cache questions (transformer)

### ISSUE THREAD

**Issue by Amruth-Vamshi** [BharatSahAIyak/packages#89]
Need a transformer which answers users question directly from bot history, if a configurable similarity matches between prev question and current question.

- [ ] Create a API at inbound/UCI to fetch similar question. (taking threshold as input) @chinmoy12c 
- [ ] Create a transformer for cache question.

**Comment by Amruth-Vamshi** [comment]
@KDwevedi to share examples

**Comment by chinmoy12c** [comment]
Duplicate https://github.com/BharatSahAIyak/orchestrator/issues/28
