### ISSUE TITLE
Cleanup common telemetry methods in transformers

### ISSUE THREAD

**Issue by chinmoy12c** [BharatSahAIyak/packages#91]
All transformers use a common function code for sending telemetry which is replicated across all transformers. This should be cleaned up and shifted to common directory.

Reference: https://github.com/BharatSahAIyak/packages/blob/b3bd0fe690bf4a8d3739aeba48aa288a2abab735/packages/transformers/src/modules/generic/http_get/http.get.transformer.ts#L82

**Comment by chinmoy12c** [comment]
@chinmoy12c to review.

**Comment by chinmoy12c** [comment]
Fixes required on orchestrator on package update v1.3.19

**Comment by BackendBananeWala** [comment]
@chinmoy12c fixes were made on the same day it self can I close this one now?
